aksClusterConfig:
  imported: true
  nodePools:
  - availabilityZones:
    - "1"
    - "2"
    - "3"
    count: 1
    enableAutoScaling: false
    maxPods: 111
    mode: System
    name: agentpool
    osDiskSizeGB: 128
    osDiskType: Managed
    osType: Linux
    vmSize: Standard_DS2_v2
  resourceGroup: auto-akshostcluster-zjtdx
  resourceLocation: eastus
awsCredentials:
azureCredentials:
  environment: AzurePublicCloud
eksClusterConfig:
  imported: true
  nodeGroups:
  - desiredSize: 1
    diskSize: 20
    ec2SshKey: ""
    gpu: false
    imageId: ""
    instanceType: t3.large
    labels: {}
    maxSize: 1
    minSize: 1
    nodeRole: ""
    nodegroupName: test1
    requestSpotInstances: false
    resourceTags: {}
    spotInstanceTypes: []
    subnets: []
    tags: {}
    userData: ""
  region: ca-central-1
gkeClusterConfig:
  projectID: container-project-qa
  zone: us-central1-c
  imported: true
  nodePools:
  - autoscaling: {}
    config:
      diskSizeGb: 100
      diskType: pd-standard
      imageType: COS_CONTAINERD
      machineType: n1-standard-2
      oauthScopes:
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/service.management.readonly
      - https://www.googleapis.com/auth/trace.append
    initialNodeCount: 1
    management:
      autoRepair: true
      autoUpgrade: true
    maxPodsConstraint: 110
    version: 1.26.5-gke.2700
googleCredentials:
rancher:
  cleanup: false
  insecure: true
