common:
labels:
  gitsha: ${{GITHUB_SHA}}

deploys:
  - name: pvala-rancher-instance
    project: container-project-qa
    region: us-central1
    instance_group: pvala-github-action-runner-instance-group
    instance_template_base: pvala-instance-template-1
    instance_template: pvala-rancher-instance-${{GITHUB_RUN_NUMBER}}-${{GITHUB_SHA}}
    cloud_init: cloud-init.yml # see example dir
    labels: # will also have gitsha from common section
      version: ${{APP_VERSION}}
    tags:
      - pvala
    update_policy:
      min_ready_sec: 60

delete_instance_templates_after: 5h