name: Secrets and Environment Variables

on:
  workflow_dispatch

jobs:
  top-secret:
    runs-on: ubuntu-latest
    env:
      EKS_REGION: ${{ vars.EKS_REGION }}

    steps:
      - name: Read a variable
        run: echo "My APP_ID value is ${{ vars.EKS_REGION }}"

      - name: Tell me a secret!
        run: echo "My existing secret is ${{ vars.AKS_CLIENT_ID }}"
      
      - name: Unset secret
        run: echo "My unknown secret is ${{ secrets.DOES_NOT_EXIST }}"
      
      - name: Github stuff
        run: echo "My Github repo is called ${{ github.repository }}"
      
      - name: Read an env variable
        run: echo "My APP_ID value is ${{ env.EKS_REGION }} (also accessible as $MY_APP_ID)"

      - uses: actions/checkout@v2
      - name: Read the env from an external script
        run: |
         chmod +x .github/scripts/custom.sh
         .github/scripts/custom.sh
        shell: bash
  
  top-secret-production:
    runs-on: ubuntu-latest
    environment: production
    env:
      APP_ID: ${{ vars.EKS_REGION }}

    steps:
      - name: Read a variable
        run: echo "My APP_ID value in the production job is $APP_ID"